### ISSUE TITLE
bug in test

### ISSUE THREAD

**Issue by charlie-becker** [NCAR/bridgescaler#1]
https://github.com/NCAR/bridgescaler/blob/dc4b9b1a27c6b5ed8c54514ea1022d3b02f7b2c3/bridgescaler/tests/group_test.py#L15

Discovered a small bug in the test. Groups are sent to the `y` argument and not used, resulting in scaling by individual columns and not by group. You could add an `assert len(groups) == len(group_scaler.scale_)` to verify.

**Comment by djgagne** [comment]
In the latest version of bridgescaler, I removed the y argument since it was not necessary for any of our purposes. The problem should be resolved.
