### ISSUE TITLE
Distributed scalers

### ISSUE THREAD

**Issue by djgagne** [NCAR/bridgescaler#5]
For datasets larger than what can be fit into memory, calculating scaling values is possible but challenging. I suggest creating a set of distributed scaler objects to operate on a file by file basis and then be added together to create the final scaling values for the dataset. MinMax scaler is pretty straightforward since you just take the min and max of all elements and can propagate that upward. 

For standard scaler, instead of calculating mean and variance, you calculate the sum of x, sum of x**2, and n for each input. You would then calculate mean and variance on the fly from these values.

For quantile transformers, you would create a histogram of values with a fixed bin width. If you stored each bin and count as a dictionary of lists, as you accumulate new bins you would tack them on the ends of the list. The quantile mapping would then be calculated on the fly from the histogram.

**Comment by charlie-becker** [comment]
Adding this [blog post](https://dataorigami.net/2015/03/19/Percentile-and-Quantile-Estimation-of-Big-Data-The-t-Digest.html) with links to code to potentially add distributed quantile estimation.

**Comment by djgagne** [comment]
Distributed quantile and other transforms have been added. Closing now.
